- hosts: all
  become: true
  roles:
    - role: commons

- hosts: db
  become: true
  roles:
    - role: mariadb

- hosts: web
  become: true
  roles:
    - role: nginx
    - role: php
    - role: varnish
    - role: wordpress
