- name: Instalaci贸n de MariaDB.
  apt:
    pkg:
      - mariadb-server
      - python-mysqldb

- name: Configuraci贸n de acceso remoto.
  template: >
    src=etc/mysql/mariadb.conf.d/50-server.cnf
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
    owner=root
    group=root
    mode=644

- name: Creaci贸n de la base de datos.
  mysql_db:
    name:
      - "{{db_mdb}}"
    state: present

- name: Creaci贸n del usuario.
  mysql_user:
    name: "{{user_mdb}}"
    password: "{{pass_mdb}}"
    priv: '{{db_mdb}}.*:ALL'
    host: "{{host_mdb}}"
    state: present
  notify: restart-mdb
