- name: Instalación de PhP.
  apt:
    pkg:
    - php7.3
    - php7.3-mysql
    - php7.3-fpm

- name: Configuración de PHP-FPM.
  template: >
    src=etc/php/7.3/fpm/pool.d/www.conf
    dest=/etc/php/7.3/fpm/pool.d/www.conf
    owner=root
    group=root
    mode=644
  notify: restart-fpm
