- name: Instalación de Varnish.
  apt:
    name: varnish

- name: Configuración de Varnish.
  copy: >
    src=etc/default/varnish
    dest=/etc/default/varnish
    owner=root
    group=root
    mode=644

- name: Configuración de la unidad systemd de Varnish.
  copy: >
    src=lib/systemd/system/varnish.service
    dest=/lib/systemd/system/varnish.service
    owner=root
    group=root
    mode=644
  notify: restart-varnish
